/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.knacrack.enhancedsurvival;

import org.junit.jupiter.api.Test;

class AppTest {

    @Test
    void appHasAGreeting() {

    }
}
